EbookWebApp/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace EbookWebApp.Models
{
    public class Order
    {
        [Required]
        public int Id { get; set; }

        public int? Rank { get; set; }

        [Required]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime OrderDate { get; set; }

        [Required]
        public int BookId { get; set; }
        public virtual Book Book { get; set; }

        [Required]
        public string AplicationUserId { get; set; }
        public virtual ApplicationUser AplicationUser { get; set; }
    }
}

EbookWebApp/ViewModels/OrderViewModel.cs
using EbookWebApp.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EbookWebApp.ViewModels
{
    public class OrderViewModel
    {
        [Required]
        public int Id { get; set; }


        public int? Rank { get; set; }

        [Required]
        [Display(Name = "Order Date")]
        [DisplayFormat(DataFormatString = "{0:dd MMMM yyyy}")]
        public DateTime OrderDate { get; set; }

        [Required]
        public int BookId { get; set; }
        public virtual Book Book { get; set; }

        [Required]
        public string AplicationUserId { get; set; }
        public virtual ApplicationUser AplicationUser { get; set; }
    }
}

EbookWebApp/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EbookWebApp.Models;
using EbookWebApp.ViewModels;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using PagedList;

namespace EbookWebApp.Controllers
{
    public class BookController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Book
        public ActionResult Index(string sortOrder, string searchString, string bookGenre, string currentFilter, int? page)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.TitleSortParm = sortOrder == "Title_desc" ? "Title_asc" : "Title_desc";
            ViewBag.AuthorSortParm = sortOrder == "Author_desc" ? "Author_asc" : "Author_desc";
            ViewBag.DateSortParm = sortOrder == "Date_desc" ? "Date_asc" : "Date_desc";
            ViewBag.RateSortParm = sortOrder == "Rate_desc" ? "Rate_asc" : "Rate_desc";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var GenreLst = new List<string>();
            var GenreQry = from d in db.Books
                           orderby d.Genre
                           select d.Genre;
            GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.bookGenre = new SelectList(GenreLst);
          
            var books = from s in db.Books
                        select s;

            foreach (var item in books.ToList())
            {
                var avgRating = db.Orders.Where(o => o.BookId == item.Id && o.Rank > 0).Select(o => o.Rank).Average();
                item.Overall = avgRating ?? 0;
            }
            db.SaveChanges();

            if (!string.IsNullOrEmpty(bookGenre))
            {
                books = books.Where(s => (s.Title.Contains(searchString) || s.Author.Contains(searchString)) && s.Genre == bookGenre);
            }
            else if (!String.IsNullOrEmpty(searchString))
            {
                books = books.Where(s => s.Title.Contains(searchString) || s.Author.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Title_desc":
                    books = books.OrderByDescending(s => s.Title);
                    break;
                case "Title_asc":
                    books = books.OrderBy(s => s.Title);
                    break;
                case "Author_desc":
                    books = books.OrderByDescending(s => s.Author);
                    break;
                case "Author_asc":
                    books = books.OrderBy(s => s.Author);
                    break;
                case "Date_desc":
                    books = books.OrderByDescending(s => s.ReleaseDate);
                    break;
                case "Date_asc":
                    books = books.OrderBy(s => s.ReleaseDate);
                    break;

                case "Rate_desc":
                    books = books.OrderByDescending(s => s.Overall);
                    break;
                case "Rate_asc":
                    books = books.OrderBy(s => s.Overall);
                    break;

                default:
                    books = books.OrderBy(s => s.Title);
                    break;
            }


            int pageSize = 10;
            int pageNumber = (page ?? 1);
           


            var vm = books.ToList().Select(x => Mapper.Map<BookViewModel>(x)).ToList();

            return View(vm.ToPagedList(pageNumber, pageSize));
            //return View(vm);
        }

        // GET: Book/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Book/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Book/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Author,Genre,ReleaseDate")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var vm = Mapper.Map<CreateBookViewModel>(book);
            return View(vm);
        }

        // GET: Book/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }

            var vm = Mapper.Map<CreateBookViewModel>(book);
            return View(vm);
        }

        // POST: Book/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Author,Genre,ReleaseDate")] Book book)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var vm = Mapper.Map<CreateBookViewModel>(book);
            return View(vm);
        }

        // GET: Book/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Book/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EbookWebApp/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using EbookWebApp.Models;
using EbookWebApp.ViewModels;
using Microsoft.AspNet.Identity;

namespace EbookWebApp.Controllers
{
    public class OrderController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Order
        [Authorize]
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                return RedirectToAction("OrderManage");
            }

            var userId = User.Identity.GetUserId();
            var orders = db.Orders.Where(u => u.AplicationUserId == userId).Include(o => o.AplicationUser).Include(o => o.Book);
            //var vm = orders.ProjectTo<OrderViewModel>().ToList();
            var vm = orders.ToList().Select(x => Mapper.Map<OrderViewModel>(x)).ToList();
            return View(vm);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult OrderManage(string searchString)
        {
            var orders = from s in db.Orders
                         select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                orders = orders.Where(s => s.AplicationUser.FirstName.Contains(searchString) 
                                                     || s.Book.Title.Contains(searchString) 
                                                     || s.Book.Author.Contains(searchString));
            }

            var vm = orders.ToList().Select(x => Mapper.Map<OrderViewModel>(x)).ToList();
            return View(vm);
        }

        // GET: Order/Get/5
        [Authorize]
        public ActionResult Get(int id)
        {
            Book book = db.Books.Find(id);
            var vm =  Mapper.Map<BookViewModel>(book);
            return View(vm);
        }

        //POST Order/Get/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Get([Bind(Include = "Id")] CreateOrderViewModel model)
        {
            var userId = User.Identity.GetUserId();
            var order = db.Orders.SingleOrDefault(o => o.BookId == model.Id && o.AplicationUserId == userId);
            if (ModelState.IsValid)
            {                
                if (order == null)
                {
                    db.Orders.Add(new Order
                    {
                        BookId = model.Id,
                        AplicationUserId = User.Identity.GetUserId()
                    });
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            Book book = db.Books.First(o => o.Id == model.Id);
            var vm = Mapper.Map<BookViewModel>(book);
            ModelState.AddModelError(String.Empty, "You already have this eBook.");
            return View(vm);
        }

        // GET: Order/Rate
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Rate(int orderid, int rank)
        {
            Order order = db.Orders.Find(orderid);
            order.Rank = rank;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Order/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EbookWebApp/Views/Order/Create.cshtml
@model EbookWebApp.Models.Order

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BookId, "BookId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BookId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BookId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AplicationUserId, "AplicationUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AplicationUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AplicationUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EbookWebApp/Views/Order/Delete.cshtml
@model EbookWebApp.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AplicationUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AplicationUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Book.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Book.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EbookWebApp/Views/Order/Get.cshtml
@using Microsoft.AspNet.Identity
@model EbookWebApp.ViewModels.BookViewModel

@{
    ViewBag.Title = "Get";
}


<h2>Dear @User.Identity.GetUserName(),</h2>
<h4>Do you want to get :</h4>

<hr />
<br/>
<table class="table margin-top-20">
    <tr class="table-warning">
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th></th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.Title)
        </td>
        <td>
            @Html.DisplayFor(model => model.Author)
        </td>
        <td>
            @Html.DisplayFor(model => model.Genre)
        </td>
    </tr>
</table>

@Html.ValidationSummary(true, "", new { @class = "text-danger" })

<div class="modal-footer">
        @Html.ActionLink("No", "Index", "Book", new {@class = "btn btn-secondary" })

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <input type="submit" value="Yes" class="btn btn-default" />
    }
</div>

EbookWebApp/Views/Order/Index.cshtml
@model IEnumerable<EbookWebApp.ViewModels.OrderViewModel>

@{
    ViewBag.Title = "Orders";
}

<h2>Your orders history:</h2>
<hr/>

<table class="table">
    <tr class="table-success">
        <th>
            @Html.DisplayNameFor(model => model.Book.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Book.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            Your rating
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="table-light">
            <td>
                @Html.DisplayFor(modelItem => item.Book.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Book.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td id="RatingControl">
                @Html.Partial("_Rating", item)
            </td>
        </tr>
    }

</table>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>

    function SetRatingControl(e) {
        var rank = $("#RatingControl a[name='Rank']");
        rank.on('click', SetRating)
    }

    function SetRating(e) {
        var data = { orderid: $(this).data("orderid"), rank: $(this).data("rank") };
        $.post("@Url.Action("Rate", "Order")", data).then(data =>  location.reload());
        
    }
    
    $(document).ready(SetRatingControl);
</script>
}

EbookWebApp/Views/Order/OrderManage.cshtml
@model IEnumerable<EbookWebApp.ViewModels.OrderViewModel>

@{
    ViewBag.Title = "OrderManage";
}

<h2>Order Manager</h2>

@using (Html.BeginForm(new { @class = "form-inline" }))
{
    <input class="form-control mr-sm-2  d-inline" id="SearchString" name="SearchString" type="text" placeholder="Search">
    <button class="btn btn-secondary my-2 my-sm-0 d-inline" type="submit">Submit</button>
}

<table class="table ">
    <tr class="table-warning">
        <th>
            @Html.DisplayNameFor(model => model.AplicationUser.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Book.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDate)
        </th>
        <th>
            Manage
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AplicationUser.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Book.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrderDate)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

EbookWebApp/Views/Order/_Rating.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
@model EbookWebApp.ViewModels.OrderViewModel

@{
    for (int i = 1; i <= 5; i++)
    {
        <a href="#" name="Rank" data-rank="@i" data-orderid="@Model.Id"> <span class="fa fa-star @(Model.Rank >= i ? "checked":"" )"></span> </a>
    }
}